### ISSUE TITLE
KeyError url

### ISSUE THREAD

**Issue by cprados** [nbr23/ydl-podcast#17] opened 2024-12-14 17:25 UTC
Hello,

I get the following: 

$ ydl-podcast -c config.yaml
ydl-podcast v1.7.10
Writing style.xsl
[youtube:tab] Extracting URL: https://www.youtube.com/@diazvillanueva/about
[youtube:tab] @diazvillanueva/about: Downloading webpage
[download] Downloading playlist: Fernando Díaz Villanueva
[info] Downloading playlist thumbnail avatar_uncropped ...
[info] Writing playlist thumbnail avatar_uncropped to: /var/www/html/podcast/Fernando Díaz Villanueva/icon.jpg
[youtube:tab] Playlist Fernando Díaz Villanueva: Downloading 0 items
[download] Finished downloading playlist: Fernando Díaz Villanueva
Traceback (most recent call last):
  File "/usr/local/bin/ydl-podcast", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/ydl_podcast/__main__.py", line 94, in main
    download(ydl_mod, sub)
  File "/usr/local/lib/python3.9/dist-packages/ydl_podcast/__init__.py", line 305, in download
    entry = get_video_metadata(ydl_mod, md["url"], options, quiet=True)
KeyError: 'url'

My config.yaml: 

subscriptions:
  - name: 'Fernando Díaz Villanueva'
    url: 'https://www.youtube.com/channel/UChojFzThpgObGHmdMS1rpvA'
    retention_days: 7 # How old is the oldest video to download and keep locally
    initialize: False # Download the whole channel on first run
    download_last: 7 # Only download the last video at each run
    audio_only: True # Extract and keep audio only
    format: mp3      # Force end format
    filename_template: '%(id)s.%(ext)s' # Use this format for files saved from this subscription

output_dir: /var/www/html/podcast/
url_root: http:///localhost/
youtube-dl-module: yt-dlp
index_enabled: False # Create an index.html file indexing the subscriptions
style_rss_feed: True # Add XSLT Styling to RSS Feed

Any hints?

**Comment by nbr23** [comment] 2024-12-14 22:51
Hey @cprados,

I'm looking into handling this better, but the issue is that you are passing the url of a page containing multiple "playlists" which confuses the module.
A quick fix would be to point directly to `https://www.youtube.com/@diazvillanueva/podcasts`, or `https://www.youtube.com/@diazvillanueva/videos` if that gives you the content you are looking for instead of the content creator's homepage.

**Comment by nbr23** [comment] 2024-12-14 23:36
OK, should be fixed as of https://github.com/nbr23/ydl-podcast/releases/tag/v1.8.0!
Thanks!

**Comment by cprados** [comment] 2024-12-15 08:43
Impressing. I tested with the URL you suggested and now it works like a charm. 

Thanks for your great work!

**Comment by nbr23** [comment] 2024-12-16 03:01
Thanks!

**Closed by nbr23** 2024-12-16 03:01 UTC
